# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='本の名前')),
                ('publisher', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('page', models.IntegerField(blank=True, default=0, verbose_name='ページ数')),
                ('how', models.IntegerField(choices=[(3, '済人'), (4, 'なし'), (1, '母'), (2, '父')], default=4, verbose_name='誰の本か')),
                ('yonda', models.IntegerField(choices=[(2, '未読'), (1, '既読')], default=2, verbose_name='本を読んだか')),
                ('genre', models.IntegerField(choices=[(4, '地理'), (5, 'プログラミング'), (10, '-------'), (9, 'わからない'), (2, '宇宙'), (6, '辞典・辞書'), (3, '歴史'), (11, '染色'), (7, '小説'), (1, '生物'), (8, '哲学')], default=10, verbose_name='ジャンル')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='登録した日付')),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='CD,DVDの名前')),
                ('genres', models.IntegerField(choices=[(7, 'その他'), (6, '宇宙'), (8, '-------'), (1, 'アニメ'), (4, '勉強用'), (5, 'クラッシック'), (2, '映画'), (3, 'コズミックフロント')], default=8, verbose_name='ジャンル')),
            ],
        ),
    ]
