# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-03 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebook', '0002_auto_20170903_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.IntegerField(choices=[(5, 'プログラミング'), (2, '宇宙'), (3, '歴史'), (6, '辞典・辞書'), (7, '小説'), (1, '生物'), (9, 'わからない'), (11, '染色'), (8, '哲学'), (4, '地理'), (10, '-------')], default=10, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='how',
            field=models.IntegerField(choices=[(3, '済人'), (1, '母'), (2, '父'), (4, 'なし')], default=4, verbose_name='誰の本か'),
        ),
        migrations.AlterField(
            model_name='book',
            name='yonda',
            field=models.IntegerField(choices=[(3, '途中'), (2, '未読'), (1, '既読')], default=2, verbose_name='本を読んだか'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='genres',
            field=models.IntegerField(choices=[(7, 'その他'), (8, '-------'), (6, '宇宙'), (1, 'アニメ'), (9, '寺'), (4, '勉強用'), (3, 'コズミックフロント'), (2, '映画'), (5, 'クラッシック')], default=8, verbose_name='ジャンル'),
        ),
    ]
